version: '3.5'
services:
  config:
    container_name: config
    build: config
    ports:
      - 8001:8001

  registry:
    container_name: registry
    restart: always
    build: registry
    ports:
      - 8761:8761
    depends_on:
      - config

  gateway:
    container_name: gateway
    restart: always
    build: gateway
    ports:
      - 8989:8989
    depends_on:
      - config
      - registry

  user-service:
    restart: on-failure
    container_name: user-service
    build: user-service
    ports:
      - 8081:8081
    depends_on:
      - config
      - registry

  book-service:
    restart: on-failure
    container_name: book-service
    build: book-service
    ports:
      - 8082:8082
    depends_on:
      - config
      - registry

  order-service:
    restart: on-failure
    container_name: order-service
    build: order-service
    ports:
      - 9998:9998
    depends_on:
      - config
      - registry

  notification:
    restart: on-failure
    container_name: notification
    build: notification
    depends_on:
      - config
      - registry

  rabbitmq: # login guest:guest
    image: rabbitmq:3-management
    hostname: rabbitmq
    labels:
      NAME: "rabbitmq"
    ports:
      - 5672:5672
      - 15672:15672
    depends_on:
      - config
      - registry
      - user-service