hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000

zuul:
  ignoredServices: '*'
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000

  routes:
    book-service:
      path: /books/**
      serviceId: book-service
      stripPrefix: false

    user-service:
      path: /users/**
      serviceId: user-service
      stripPrefix: false

    order-service:
      path: /orders/**
      serviceId: order-service
      stripPrefix: false

server:
  port: 8989